### ISSUE TITLE
document which PPL commands have persistent effects

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#665] opened 2017-11-23 02:23 UTC
**Reported by @AnsleyManke on 31 Jan 2006 21:52 UTC**
Some PPL commands have persistent effects, others are reset with each new plot
command.  This should be in the documentation.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1386

**Comment by AnsleyManke** [comment] 2019-08-29 17:07
duplicate of #664

**Closed by AnsleyManke** 2019-08-29 17:07 UTC
Labels: P: high, S: normal, bug
