### ISSUE TITLE
add /LIKE= qualifiers for DEFINE AXIS and LET

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#138] opened 2017-11-21 22:33 UTC
**Reported by steven.c.hankin on 3 Aug 2001 21:44 UTC**
DEFINE AXIS/LIKE=existing/units=foobars new_axis

LET/LIKE=existing/units="deg F" new = 9/5 * existing + 32

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/303

**Comment by AnsleyManke** [comment] 2018-02-28 00:02
This is a duplicate of issue #966

**Closed by AnsleyManke** 2018-02-28 00:02 UTC
Labels: P: high, enhancement
