### ISSUE TITLE
immediate mode evaluation crashes Ferret

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1929] opened 2019-05-06 15:53 UTC
John Krasting at GFDL reported this bug, which is causing failures of our automated diagnostic scripts.  A quick fix would be appreciated, to avoid our having to revert back to an old version of Ferret.  This bug appears to have been introduced between v7.4202 (8/9/18) and v7.4203 (8/20/18).  

```
 	NOAA/PMEL TMAP
 	FERRET v7.5 (optimized)
 	Linux 2.6.32-754.11.1.el6.x86_64 64-bit - 04/25/19
 	 6-May-19 11:46     

yes? say `2.2100001 * 1e8`
 !-> MESSAGE/CONTINUE 221000010
221000010
yes? say `2.2100001 * 1e9`
At line 331 of file tm_fmt_user.F
Fortran runtime error: Nonnegative width required in format
(F**.**)  
  ^
```

**Comment by eugeneburger** [comment] 2019-05-06 16:22
Hello Andrew - noted.

**Comment by karlmsmith** [comment] 2019-05-06 17:29
At some point the value is rounded to the nearest integer as an `INTEGER*4` using NINT (then assigned to `REAL*8`) to do some checks.  Because of the magnitude of the value, this overflows and becomes a negative integer.  Need to modify the check to convert to the nearest integer value as a `REAL*8` using DNINT.

**Comment by karlmsmith** [comment] 2019-05-07 05:59
Getting close to finishing this.  Unifying the TM_FMT* functions so fixes do not have to be repeated as much.  Dealing with large integers by writing as `F<n>.0` then letting code later on trim off the dot (if present).  Still working on getting the decision of whether to write as an integer versus writing in "E" format back in place.  The fixes and clean-up should (hopefully) result in more robust code.  

The values showing this bug are those that overflow an `INTEGER*4` value but can still be written in the  allowed width as an integer value; ie, not so big they have to be written in "E" format.

**Comment by karlmsmith** [comment] 2019-05-07 15:58
Updated `TM_FMT*` functions to handle integer values that would overflow `INTEGER*4`.
(Values more than `2**32 - 1` but less than `10**9` previously would cause an overflow.)

`TM_FMT_SNGL` is just a wrapper around `TM_FMT`.

`TM_FMT_SNGL_DIGIT` calls `TM_FMT` and adds any needed additional precision digits 
(which will be zeros).

Restriction on values printed as integers be no more than eight characters removed
since this is no longer necessary.

Also all these functions now return `CHARACTER*64` since that was the max size supported.
Return values assigned to shorter strings will be truncated when assigned in the calling code.
In essence, `max_len` argument can be used similar to the `digits` argument, 
especially if the `digits` argument giving precision (negative).

Bench test results NOT updated as there are some side-effects of removing the integer
restriction give results that are correct but probably undesirable.
These should probably be fixed by changing the `max_len` value passed (do not allow
a large number of characters if you really do not want to see that many characters).
May still need some tweaking, but wanted to get this checked into the svn repo (NOT in GitHub yet) and then work from there this afternoon.

**Comment by karlmsmith** [comment] 2019-05-08 19:29
Modified `max_len` values in calls to `TM_FMT*` functions so that very long numeric strings are no longer produced.  The output mostly matches previous output; where it does not is due to integer values allowed to be longer than 8 characters (showing 10 character integers, but not showing 33 character integers).  A couple of exceptions still are
```code
   yes? say `1.555555551e-9,p=10`
    !-> MESSAGE/CONTINUE 1.55556E-09
```
and with lev_v_levels.gif (key labels too long), which needs further investigation.

Want to look into why `TM_FMT` does not precisely follow the provided number of significant digits or precision that is passed to it.  (The current fix uses the `TM_FMT_USER` function is more of a work-around rather than a fix.)  If it can be fixed, see what changes and if looks good, check that in and remove `TM_FMT_USER`.

But updates are in latest Ferret and PyFerret GitHub code.

@AndrewWittenberg - getting this version built at GFDL so you can move past this roadblock.  Hopefully the changes do not cause other issues.

**Comment by AndrewWittenberg** [comment] 2019-06-10 17:46
Unfortunately the fix is causing an even worse problem -- silently returning a result that is wrong by several orders of magnitude!

In v7.4202 (8/9/18) we had the right answer:
```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 08/09/18
 	10-Jun-19 13:41     

yes? say `2.2100001 * 1e9`
2.2100001E+09
yes? say `2.2100001 * 1e13`
2.2100001E+13
```

But in v7.5001 (5/8/19) we get:
```
ldt-4295213:/home/atw> ferret
 	NOAA/PMEL TMAP
 	FERRET v7.5001 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 05/08/19
 	10-Jun-19 13:42     

yes? say `2.2100001 * 1e9`
 !-> MESSAGE/CONTINUE 2210000100
2210000100
yes? say `2.2100001 * 1e13`
 !-> MESSAGE/CONTINUE 22100001
22100001
```

I'd still classify this as urgent -- it is bringing down my automated scripts as well as John's.

**Comment by AnsleyManke** [comment] 2019-06-10 17:47
Rats.  That fix was always going to need more work.  Thanks for the testing.

**Comment by AnsleyManke** [comment] 2019-06-10 22:22
The value gets formatted correctly by tm_fmt but then the string-length was incorrectly shortened in the tests for string representation that's 5.000001 or 4.999999 that really should be returned as 5.

**Comment by AndrewWittenberg** [comment] 2019-06-11 17:39
Thanks for the fixes!  That allows us to move forward.

Note though, there are still a few more related minor issues in v7.502:
```
 	NOAA/PMEL TMAP
 	FERRET v7.502 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 06/11/19
 	11-Jun-19 13:15     

yes? say `1234567890123456`
1234567890123456
yes? say `12345678901234567`
12345678901234568
yes? say `123456789012345678`
123456789012345680
yes? say `1234567890123456789`
1234567890123456768
yes? say `12345678901234567890`
12345678901234567168
yes? say `123456789012345678901`
123456789012345683968
yes? say `1234567890123456789012`
1234567890123456774144
yes? say `12345678901234567890123`
1.234567890123457E+22
yes? say `123456789012345678901234`
1.234567890123457E+23
```

The largest number returned as an integer is 22 digits long, but only the first 16 significant figures are reliable.  I'd suggest shifting into scientific notation whenever the longest integer would exceed 16 sigfigs.

Earlier versions (e.g. v7.42) had a similar issue, although the longest integer returned was 19 rather than 22 digits:

```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-754.el6.x86_64 64-bit - 07/10/18
 	11-Jun-19 13:17     

yes? say `1234567890123456`
1234567890123456.
yes? say `12345678901234567`
12345678901234568.
yes? say `123456789012345678`
123456789012345680.
yes? say `1234567890123456789`
1234567890123456768.
yes? say `12345678901234567890`
1.234567890123457E+19
yes? say `123456789012345678901`
1.234567890123457E+20
yes? say `1234567890123456789012`
1.234567890123457E+21
yes? say `12345678901234567890123`
1.234567890123457E+22
yes? say `123456789012345678901234`
1.234567890123457E+23
```

Ferret should also trim any leading zeroes before the decimal point, prior to converting to a number:
```
yes? say `00000000000000000012345678901234567890`
123456
yes? say `000000000000000000.12345678901234567890`
0.12345
```
The first answer is wrong by many orders of magnitude, while the second unnecessarily loses precision.

It'd be good to subject the number-conversion to more stress testing (invalid characters etc.) and add benchmarks for all of these examples.

**Comment by AndrewWittenberg** [comment] 2019-06-19 22:12
Just discovered these further examples in our automated diagnostics that crash Ferret.  Bumping the priority up to "urgent" again.

The following works as expected:

```
 	NOAA/PMEL TMAP
 	FERRET v7.502 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 06/11/19
 	19-Jun-19 17:56     

yes? say `1e-5,p=-1`
0.00001
```

But all of the following crash Ferret v7.502:
```
 	NOAA/PMEL TMAP
 	FERRET v7.502 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 06/11/19
 	19-Jun-19 18:10     

yes? say `1e-6,p=-1`
At line 1291 of file repl_exprns.F
Fortran runtime error: Bad real number in item 1 of list input

yes? say `1e-7,p=-1`
At line 240 of file tm_fmt_user.F
Fortran runtime error: Nonnegative width required in format
(1PG 1.-1)
        ^

yes? say `1e-11,p=-1`
At line 240 of file tm_fmt_user.F
Fortran runtime error: Nonnegative width required in format
(1PG-3.-5)
     ^
```

Here's what we got in the old v7.4202 (8/9/18):
```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 08/09/18
 	19-Jun-19 18:09     

yes? can mode verify
yes? say `1e-6,p=-1`
0.000001
yes? say `1e-7,p=-1`
0.0000001
yes? say `1e-11,p=-1`
0.00000000001
```

Would it be possible to build a unit-test for Ferret that systematically checks all possible types of numbers and formats, so that these bugs don't keep cropping up?  E.g. run through the allowed exponents, precisions, etc.  Even just checking for crashes would be helpful.

**Comment by karlmsmith** [comment] 2019-06-20 00:03
Seems like 
```
`1E-6,p=-1` 
`1.0E-7,p=-1`
`1.0E-11,p=-1`
```
all properly should return ```0.0``` (one decimal point of precision).  Or do you want it to return the same values as before (which would actually be ```p=1```)?

**Comment by karlmsmith** [comment] 2019-06-20 00:08
Why I ask is: do we ago back to the original code and problem and try to find a minimal fix, or do we pursue the revised code that seems more in line with other definitions of `p=...`?

BTW - The crash issue appear to be trying to see if a shorter representation would be more appropriate, but it then tries to evaluate `*****` as a floating point number

**Comment by AndrewWittenberg** [comment] 2019-06-20 01:13
I'd vote for ``` `1.0E-11,p=-1` ``` returning 0.0, rather than the old behavior of returning at least 1 sigfig even if it was far past the first decimal point.  Note that this would require a change in the documentation [here](https://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/variables-xpressions/EMBEDDED-XPRESSIONS#_VPINDEXENTRY_570), where it says:

"This also means that Ferret will always return at least one significant digit:``` SAY `0.123,P=0` ``` will result in 0.1"

**Comment by AnsleyManke** [comment] 2019-06-20 16:13
I agree, making the distinction between negative and positive values for the precision number mean what we say it does.

Overall the code will be much simplified and improved, and will be easier to maintain once we get these wrinkles out, and we'll get a bunch more variety into our  benchmark tests.

**Comment by AnsleyManke** [comment] 2019-06-20 23:47
The behavior in the examples like

yes? say `00000000000000000012345678901234567890`

is happening at command parsing not the formatting of numbers in immediate mode evaluation. It's an easy fix in constant_context.F

**Comment by karlmsmith** [comment] 2019-06-28 00:14
All the issues mentioned in this ticket should be fixed in the latest Ferret https://github.com/NOAA-PMEL/Ferret/commit/fca15acc61693764665a97c9b5c0a8fad92848de and PyFerret https://github.com/NOAA-PMEL/PyFerret/commit/f0b54035c48a03741301fdf24b4b454e8b2d7a31

**Closed by karlmsmith** 2019-06-28 00:14 UTC
Labels: GFDL: urgent, P: highest, S: blocker, bug

**Comment by AndrewWittenberg** [comment] 2019-06-28 01:06
Thanks!  For the public release, don't forget to change the documentation as mentioned above.

**Comment by AndrewWittenberg** [comment] 2019-06-28 01:20
One more minor wrinkle:

```
 	NOAA/PMEL TMAP
 	FERRET v7.503 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 06/27/19
 	27-Jun-19 21:17     

yes? say `2.2 * 1e41,p=-5`
220000000000000028443960000000000000000000.00000
yes? say `2.2 * 1e42,p=-5`
******
```

What to do here?  Should these return 2.20000e41 and 2.200000e42?  I'll go with whatever precedent is relevant.

**Comment by karlmsmith** [comment] 2019-06-28 01:45
The behavior we are following is that negative values gives the number of digits after the decimal point.  So in this case, F48.5 (48 being the max string length for output).   The non-zero digits in the middle of that string is from the expected numerical error in double-precision representation.  The second output cannot be stuffed into that format, thus the '*****'.

Using p=5 will give you the exponential values.  Except that it will trim off the zeros to shorten the string and "pretty it up".  If the value was 2.2345 , then you would see all five digits.

**Comment by AnsleyManke** [comment] 2019-06-28 16:23
The issue is getting decent results in cases where we don't know the values ahead of time

previous code returned 
2.2E+41
2.2E+42

We might look again at the idea of computing the string with both a fixed and exponential formats (maybe whenever the automatic choice has resulted in a "long" string, whatever we determine that to be)

**Comment by AnsleyManke** [comment] 2019-06-28 16:24
Andrew, the other general place this rewrite of the underlying code may show itself is in the labels  on plots, such as the labels along colorbars.  Keep an eye out for anything that looks oddball and let us know.

**Comment by AndrewWittenberg** [comment] 2019-06-28 17:36
Thanks for the heads-up!  Here are a few oddities:

```
 	NOAA/PMEL TMAP
 	FERRET v7.503 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 06/27/19
 	28-Jun-19 13:23     

yes? use coads_climatology; set reg/l=1
yes? shade sst * 1e-6       ! flips back & forth between decimal & scientific
yes? shade sst * 1e-12   ! this looks good, ...
yes? shade sst * 1e-13     ! ...but this suddenly transitions to way more digits
yes? shade sst * 1e-39   ! this gives a blank plot
yes? shade sst * 1e-47   ! this gives a constant-zero plot
yes? shade/l=1 sst * 1e4   ! too much precision on some key labels
yes? shade/l=1 sst * 1e34  ! many values interpreted as missing (same for 1e35 to 1e38)
yes? shade/l=1 sst * 1e39  ! blank plot
```

Might be good to add these to your test suite.

**Comment by AnsleyManke** [comment] 2019-06-28 18:19
Actually this brings to mind something we've talked about a few times; that the plot algorithm could scale the data and then plot with a rationally-labeled colorbar that's labeled with the scale factor. No matter what, labels that say 1.2E-12, 1.4E-11, etc aren't great.

**Comment by AnsleyManke** [comment] 2019-07-01 18:40
I've added plots like these to our tests, and repaired the issues causing the bad key labels.

yes? use coads_climatology; set reg/l=1
yes? shade sst * 1e-6       ! flips back & forth between decimal & scientific
yes? shade sst * 1e-12   ! this looks good, ...
yes? shade sst * 1e-13     ! ...but this suddenly transitions to way more digits
yes? shade/l=1 sst * 1e4   ! too much precision on some key labels


The remaining plots with super large or small values cannot be plotted correctly using PPLUS.  (This behavior is not new.) We would need to automatically rescale the data before passing it into the plotting routines.   I'll make a new ticket on that.
